config/routes.rb
Rails.application.routes.draw do
  resources :fantasy_drafts
  resources :fantasy_draft_orders
  resources :fantasy_draft_styles
  resources :fantasy_players
  resources :fantasy_teams
  resources :fantasy_leagues
  resources :player_auction_values
  resources :player_projections
  resources :player_ranks
  resources :players
  resources :positions
  resources :byes
  resources :schedules
  resources :teams
  resources :leagues

  resources :fantasy_leagues do
    resources :fantasy_drafts
    resources :fantasy_teams do
      resources :fantasy_players
    end
    resources :fantasy_drafts do
      get '/manager', to: 'fantasy_drafts#manager'
      get '/cheatsheet', to: 'fantasy_drafts#cheatsheet'
      get '/report', to: 'fantasy_drafts#report'
      resources :fantasy_players
      resources :fantasy_draft_orders
    end
  end

  root 'fantasy_leagues#index'
end

app/models/bye.rb
class Bye < ActiveRecord::Base
  belongs_to :team
end

app/models/fantasy_draft.rb
class FantasyDraft < ActiveRecord::Base
  belongs_to :fantasy_league
  belongs_to :fantasy_draft_style
  belongs_to :player

end

app/models/fantasy_draft_order.rb
class FantasyDraftOrder < ActiveRecord::Base
  belongs_to :fantasy_league
  belongs_to :fantasy_team
  belongs_to :fantasy_draft
end

app/models/fantasy_league.rb
class FantasyLeague < ActiveRecord::Base
    has_many :fantasy_teams
    has_many :fantasy_drafts
end

app/models/fantasy_player.rb
class FantasyPlayer < ActiveRecord::Base
  belongs_to :fantasy_league
  belongs_to :fantasy_team
  belongs_to :fantasy_draft
  belongs_to :player
end

app/models/fantasy_team.rb
class FantasyTeam < ActiveRecord::Base
    belongs_to :fantasy_league


    def name_and_owner
        "#{name} - #{owner}"
    end

    def owner_and_team
        "#{owner} - #{name}"
    end

end

app/models/league.rb
class League < ActiveRecord::Base
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :league
  belongs_to :team
  belongs_to :position
  has_one :player_auction_value
  has_one :player_projection
  has_one :player_rank

    def age
      (Time.now.to_s(:number).to_i - date_of_birth.to_time.to_s(:number).to_i)/10e9.to_i
    end

end

app/models/player_projection.rb
class PlayerProjection < ActiveRecord::Base
  belongs_to :player
  has_one :team, through: :player
  has_one :position, through: :player
end

app/models/player_rank.rb
class PlayerRank < ActiveRecord::Base
  belongs_to :player
  has_one :team, through: :player
  has_one :position, through: :player
end

app/models/position.rb
class Position < ActiveRecord::Base
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :away_team, class_name: "Team", foreign_key: "away_team_id"
  belongs_to :home_team, class_name: "Team", foreign_key: "home_team_id"
end

app/models/team.rb
class Team < ActiveRecord::Base
    belongs_to :league
    has_many :players
    has_many :schedules
    has_one :bye

    def full_name
        "#{city} #{name}"
    end
end

app/controllers/fantasy_leagues_controller.rb
class FantasyLeaguesController < ApplicationController
  before_action :set_fantasy_league, only: [:edit, :update, :destroy]

  # GET /fantasy_leagues
  # GET /fantasy_leagues.json
  def index
    @fantasy_leagues = FantasyLeague.all
  end

  # GET /fantasy_leagues/1
  # GET /fantasy_leagues/1.json
  def show
    @fantasy_league = FantasyLeague.includes(:fantasy_teams, :fantasy_drafts).find(params[:id])
  end

  # GET /fantasy_leagues/new
  def new
    @fantasy_league = FantasyLeague.new
  end

  # GET /fantasy_leagues/1/edit
  def edit
  end

  # POST /fantasy_leagues
  # POST /fantasy_leagues.json
  def create
    @fantasy_league = FantasyLeague.new(fantasy_league_params)

    respond_to do |format|
      if @fantasy_league.save
        format.html { redirect_to @fantasy_league, notice: 'Fantasy league was successfully created.' }
        format.json { render :show, status: :created, location: @fantasy_league }
      else
        format.html { render :new }
        format.json { render json: @fantasy_league.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fantasy_leagues/1
  # PATCH/PUT /fantasy_leagues/1.json
  def update
    respond_to do |format|
      if @fantasy_league.update(fantasy_league_params)
        format.html { redirect_to @fantasy_league, notice: 'Fantasy league was successfully updated.' }
        format.json { render :show, status: :ok, location: @fantasy_league }
      else
        format.html { render :edit }
        format.json { render json: @fantasy_league.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fantasy_leagues/1
  # DELETE /fantasy_leagues/1.json
  def destroy
    @fantasy_league.destroy
    respond_to do |format|
      format.html { redirect_to fantasy_leagues_url, notice: 'Fantasy league was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fantasy_league
      @fantasy_league = FantasyLeague.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fantasy_league_params
      params.require(:fantasy_league).permit(:name, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/byes_helper.rb
module ByesHelper
end

app/helpers/drafts_helper.rb
module DraftsHelper
end

app/helpers/fantasy_leagues_helper.rb
module FantasyLeaguesHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/fantasy_leagues/_form.html.erb
<%= form_for(@fantasy_league) do |f| %>
  <% if @fantasy_league.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fantasy_league.errors.count, "error") %> prohibited this fantasy_league from being saved:</h2>

      <ul>
      <% @fantasy_league.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fantasy_leagues/edit.html.erb
<h1>Editing fantasy_league</h1>

<%= render 'form' %>

<%= link_to 'Show', @fantasy_league %> |
<%= link_to 'Back', fantasy_leagues_path %>

app/views/fantasy_leagues/index.html.erb
<h4>Fantasy Leagues</h4>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @fantasy_leagues.each do |fantasy_league| %>
      <tr>
        <td><%= link_to fantasy_league.name, fantasy_league %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fantasy league', new_fantasy_league_path %>

app/views/fantasy_leagues/new.html.erb
<h1>New fantasy_league</h1>

<%= render 'form' %>

<%= link_to 'Back', fantasy_leagues_path %>

app/views/fantasy_leagues/show.html.erb
<h3>
    <%= @fantasy_league.name %>
    <small>
        <%= link_to '[ League Settings ]', edit_fantasy_league_path(@fantasy_league), :class => 'btn-link' %>
    </small>
</h3>
<hr />

<div class="row-fluid">
    <div class="span6">
        <div class="pull-right">
            <%= link_to 'Add New Team', new_fantasy_league_fantasy_team_path(@fantasy_league), :class => 'btn' %>
        </div>
        <h4>Teams</h4>
        <hr />

        <table class="table">
          <thead>
            <tr>
              <th width="45%">Team</th>
              <th width="">Owner</th>
              <th width="25%"></th>
            </tr>
          </thead>

          <tbody>
            <% @fantasy_league.fantasy_teams.each do |fantasy_team| %>
              <tr>
                <td><%= fantasy_team.name %></td>
                <td><%= fantasy_team.owner %></td>
                <td>
                    <%= link_to 'Edit', edit_fantasy_league_fantasy_team_path(@fantasy_league, fantasy_team), :class => 'btn btn-mini' %>
                    <%= link_to 'Delete', fantasy_league_fantasy_team_path(@fantasy_league, fantasy_team), :class => 'btn btn-mini btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

    </div>
    <div class="span6">
        <div class="pull-right">
            <%= link_to 'Add New Draft', new_fantasy_league_fantasy_draft_path(@fantasy_league), :class => 'btn' %>
        </div>
        <h4>Drafts</h4>
        <hr />

        <table class="table">
          <thead>
            <tr>
              <th>Style</th>
              <th>Rounds</th>
              <th>Max Amount</th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <% @fantasy_league.fantasy_drafts.each do |fantasy_draft| %>
              <tr>
                <td><%= fantasy_draft.fantasy_draft_style.name %> Draft</td>
                <td><%= fantasy_draft.rounds %></td>
                <td>$<%= fantasy_draft.max_amount %></td>
                <td>

                  <div class="btn-group">
                    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                      Actions
                      <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                      <li>
                        <%= link_to 'Draft Board', fantasy_league_fantasy_draft_path(@fantasy_league, fantasy_draft) %>
                      </li>
                      <li>
                        <%= link_to 'Cheat Sheet', fantasy_league_fantasy_draft_cheatsheet_path(@fantasy_league, fantasy_draft) %>
                      </li>
                      <li>
                        <%= link_to 'Report Card', fantasy_league_fantasy_draft_report_path(@fantasy_league, fantasy_draft) %>
                      </li>
                      <li>
                        <%= link_to 'Manager', fantasy_league_fantasy_draft_manager_path(@fantasy_league, fantasy_draft) %>
                      </li>
                      <li>
                        <%= link_to 'Set Draft Order', fantasy_league_fantasy_draft_fantasy_draft_orders_path(@fantasy_league, fantasy_draft) %>
                      </li>

                      <li>
                        <%= link_to 'Settings', edit_fantasy_league_fantasy_draft_path(@fantasy_league, fantasy_draft) %>
                      </li>
                    </ul>
                  </div>

                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

    </div>
</div>