config/routes.rb
Rails.application.routes.draw do
  resources :fantasy_drafts
  resources :fantasy_draft_orders
  resources :fantasy_draft_styles
  resources :fantasy_players
  resources :fantasy_teams
  resources :fantasy_leagues
  resources :player_auction_values
  resources :player_projections
  resources :player_ranks
  resources :players
  resources :positions
  resources :byes
  resources :schedules
  resources :teams
  resources :leagues

  resources :fantasy_leagues do
    resources :fantasy_drafts
    resources :fantasy_teams do
      resources :fantasy_players
    end
    resources :fantasy_drafts do
      get '/manager', to: 'fantasy_drafts#manager'
      get '/cheatsheet', to: 'fantasy_drafts#cheatsheet'
      get '/report', to: 'fantasy_drafts#report'
      resources :fantasy_players
      resources :fantasy_draft_orders
    end
  end

  root 'fantasy_leagues#index'
end

app/models/bye.rb
class Bye < ActiveRecord::Base
  belongs_to :team
end

app/models/fantasy_draft.rb
class FantasyDraft < ActiveRecord::Base
  belongs_to :fantasy_league
  belongs_to :fantasy_draft_style
  belongs_to :player

end

app/models/fantasy_draft_style.rb
class FantasyDraftStyle < ActiveRecord::Base
end

app/models/fantasy_league.rb
class FantasyLeague < ActiveRecord::Base
    has_many :fantasy_teams
    has_many :fantasy_drafts
end

app/models/fantasy_player.rb
class FantasyPlayer < ActiveRecord::Base
  belongs_to :fantasy_league
  belongs_to :fantasy_team
  belongs_to :fantasy_draft
  belongs_to :player
end

app/models/fantasy_team.rb
class FantasyTeam < ActiveRecord::Base
    belongs_to :fantasy_league


    def name_and_owner
        "#{name} - #{owner}"
    end

    def owner_and_team
        "#{owner} - #{name}"
    end

end

app/models/league.rb
class League < ActiveRecord::Base
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :league
  belongs_to :team
  belongs_to :position
  has_one :player_auction_value
  has_one :player_projection
  has_one :player_rank

    def age
      (Time.now.to_s(:number).to_i - date_of_birth.to_time.to_s(:number).to_i)/10e9.to_i
    end

end

app/models/player_projection.rb
class PlayerProjection < ActiveRecord::Base
  belongs_to :player
  has_one :team, through: :player
  has_one :position, through: :player
end

app/models/player_rank.rb
class PlayerRank < ActiveRecord::Base
  belongs_to :player
  has_one :team, through: :player
  has_one :position, through: :player
end

app/models/position.rb
class Position < ActiveRecord::Base
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :away_team, class_name: "Team", foreign_key: "away_team_id"
  belongs_to :home_team, class_name: "Team", foreign_key: "home_team_id"
end

app/models/team.rb
class Team < ActiveRecord::Base
    belongs_to :league
    has_many :players
    has_many :schedules
    has_one :bye

    def full_name
        "#{city} #{name}"
    end
end

app/controllers/fantasy_draft_styles_controller.rb
class FantasyDraftStylesController < ApplicationController
  before_action :set_fantasy_draft_style, only: [:show, :edit, :update, :destroy]

  # GET /fantasy_draft_styles
  # GET /fantasy_draft_styles.json
  def index
    @fantasy_draft_styles = FantasyDraftStyle.all
  end

  # GET /fantasy_draft_styles/1
  # GET /fantasy_draft_styles/1.json
  def show
  end

  # GET /fantasy_draft_styles/new
  def new
    @fantasy_draft_style = FantasyDraftStyle.new
  end

  # GET /fantasy_draft_styles/1/edit
  def edit
  end

  # POST /fantasy_draft_styles
  # POST /fantasy_draft_styles.json
  def create
    @fantasy_draft_style = FantasyDraftStyle.new(fantasy_draft_style_params)

    respond_to do |format|
      if @fantasy_draft_style.save
        format.html { redirect_to @fantasy_draft_style, notice: 'Fantasy draft style was successfully created.' }
        format.json { render :show, status: :created, location: @fantasy_draft_style }
      else
        format.html { render :new }
        format.json { render json: @fantasy_draft_style.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fantasy_draft_styles/1
  # PATCH/PUT /fantasy_draft_styles/1.json
  def update
    respond_to do |format|
      if @fantasy_draft_style.update(fantasy_draft_style_params)
        format.html { redirect_to @fantasy_draft_style, notice: 'Fantasy draft style was successfully updated.' }
        format.json { render :show, status: :ok, location: @fantasy_draft_style }
      else
        format.html { render :edit }
        format.json { render json: @fantasy_draft_style.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fantasy_draft_styles/1
  # DELETE /fantasy_draft_styles/1.json
  def destroy
    @fantasy_draft_style.destroy
    respond_to do |format|
      format.html { redirect_to fantasy_draft_styles_url, notice: 'Fantasy draft style was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fantasy_draft_style
      @fantasy_draft_style = FantasyDraftStyle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fantasy_draft_style_params
      params.require(:fantasy_draft_style).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/byes_helper.rb
module ByesHelper
end

app/helpers/drafts_helper.rb
module DraftsHelper
end

app/helpers/fantasy_draft_styles_helper.rb
module FantasyDraftStylesHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/fantasy_draft_styles/_form.html.erb
<%= form_for(@fantasy_draft_style) do |f| %>
  <% if @fantasy_draft_style.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fantasy_draft_style.errors.count, "error") %> prohibited this fantasy_draft_style from being saved:</h2>

      <ul>
      <% @fantasy_draft_style.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fantasy_draft_styles/edit.html.erb
<h1>Editing fantasy_draft_style</h1>

<%= render 'form' %>

<%= link_to 'Show', @fantasy_draft_style %> |
<%= link_to 'Back', fantasy_draft_styles_path %>

app/views/fantasy_draft_styles/index.html.erb
<h1>Listing fantasy_draft_styles</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fantasy_draft_styles.each do |fantasy_draft_style| %>
      <tr>
        <td><%= fantasy_draft_style.name %></td>
        <td><%= link_to 'Show', fantasy_draft_style %></td>
        <td><%= link_to 'Edit', edit_fantasy_draft_style_path(fantasy_draft_style) %></td>
        <td><%= link_to 'Destroy', fantasy_draft_style, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fantasy draft style', new_fantasy_draft_style_path %>

app/views/fantasy_draft_styles/new.html.erb
<h1>New fantasy_draft_style</h1>

<%= render 'form' %>

<%= link_to 'Back', fantasy_draft_styles_path %>

app/views/fantasy_draft_styles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fantasy_draft_style.name %>
</p>

<%= link_to 'Edit', edit_fantasy_draft_style_path(@fantasy_draft_style) %> |
<%= link_to 'Back', fantasy_draft_styles_path %>