config/routes.rb
Rails.application.routes.draw do
  resources :fantasy_drafts
  resources :fantasy_draft_orders
  resources :fantasy_draft_styles
  resources :fantasy_players
  resources :fantasy_teams
  resources :fantasy_leagues
  resources :player_auction_values
  resources :player_projections
  resources :player_ranks
  resources :players
  resources :positions
  resources :byes
  resources :schedules
  resources :teams
  resources :leagues

  resources :fantasy_leagues do
    resources :fantasy_drafts
    resources :fantasy_teams do
      resources :fantasy_players
    end
    resources :fantasy_drafts do
      get '/manager', to: 'fantasy_drafts#manager'
      get '/cheatsheet', to: 'fantasy_drafts#cheatsheet'
      get '/report', to: 'fantasy_drafts#report'
      resources :fantasy_players
      resources :fantasy_draft_orders
    end
  end

  root 'fantasy_leagues#index'
end

app/models/fantasy_draft.rb
class FantasyDraft < ActiveRecord::Base
  belongs_to :fantasy_league
  belongs_to :fantasy_draft_style
  belongs_to :player

end

app/controllers/fantasy_drafts_controller.rb
class FantasyDraftsController < ApplicationController
  before_action :set_fantasy_draft, only: [:edit, :update, :destroy]

  # GET /drafts
  # GET /drafts.json
  def index
    @fantasy_drafts = FantasyDraft.all
  end

  def report
    @fantasy_league = FantasyLeague.includes(:fantasy_teams).find(params[:fantasy_league_id])
  end


  def cheatsheet

    @fantasy_players = FantasyPlayer.where(fantasy_draft_id: params[:fantasy_draft_id], fantasy_league_id: params[:fantasy_league_id]).order('id DESC')

    if params[:position_id]
      if @fantasy_players.any?
        @player_ranks = PlayerRank.joins(:player, :team, :position).where('player_id not in (?)', @fantasy_players.map(&:player_id)).where('positions.id = ?', params[:position_id]).order('position_rank ASC')
      else
        @player_ranks = PlayerRank.joins(:player, :team, :position).where('positions.id = ?', params[:position_id]).order('position_rank ASC')
      end
    else
      if @fantasy_players.any?
        @player_ranks = PlayerRank.includes(:player, :team, :position).where('player_id not in (?)', @fantasy_players.map(&:player_id)).order('overall_rank ASC')
      else
        @player_ranks = PlayerRank.includes(:player, :team, :position).order('overall_rank ASC')
      end
    end
    render layout: "cheatsheet"
  end



  def manager
    @fantasy_league = FantasyLeague.includes(:fantasy_teams).find(params[:fantasy_league_id])
    @fantasy_draft = FantasyDraft.find(params[:fantasy_draft_id])
    @fantasy_players = FantasyPlayer.where(fantasy_draft_id: params[:fantasy_draft_id], fantasy_league_id: params[:fantasy_league_id]).order('id DESC')

    if @fantasy_players.any?
      @players = Player.all.order('name').where('id not in (?)', @fantasy_players.map(&:player_id)).includes(:position, :team).map { |player| ["#{player.name} (#{player.position.name}) - #{player.team.key} ",player.id]}
    else
      @players = Player.all.order('name').includes(:position, :team).map { |player| ["#{player.name} (#{player.position.name}) - #{player.team.key} ",player.id]}
    end

    @fantasy_player = FantasyPlayer.new(:fantasy_league_id => params[:fantasy_league_id], :fantasy_draft_id => params[:fantasy_draft_id])

  end

  # GET /drafts/1
  # GET /drafts/1.json
  def show
    @fantasy_league       = FantasyLeague.includes(:fantasy_teams).find(params[:fantasy_league_id])
    @fantasy_draft        = FantasyDraft.find(params[:id])
    @fantasy_draft_orders = FantasyDraftOrder.where(fantasy_league_id: params[:fantasy_league_id], fantasy_draft_id: params[:id]).order('position ASC')
    @fantasy_players      = FantasyPlayer.where(fantasy_draft_id: params[:id], fantasy_league_id: params[:fantasy_league_id]).order('id DESC')


    temp_keys = Array.new
    temp_counter = 0
    @fantasy_players.each do
      temp_keys << temp_counter
      temp_counter += 1
    end

    # raise temp_keys.to_yaml
    # raise @fantasy_players.to_yaml

    # Build out the fantasy order so we can easily loop through it
    @fantasy_order = Array.new

    counter = 0
    @fantasy_draft.rounds.times do

      @fantasy_draft_orders.each do |fantasy_draft_order|
        if not temp_keys.include? counter
          @fantasy_order << fantasy_draft_order.fantasy_team
        end
        counter += 1
      end

    end

    render layout: "draft_board"
  end

  # GET /drafts/new
  def new
    @fantasy_league = FantasyLeague.find(params[:fantasy_league_id])
    @fantasy_draft = FantasyDraft.new(:fantasy_league_id => params[:fantasy_league_id])
  end

  # GET /drafts/1/edit
  def edit
    @fantasy_league = FantasyLeague.find(params[:fantasy_league_id])
  end

  # POST /drafts
  # POST /drafts.json
  def create
    @fantasy_draft = FantasyDraft.new(fantasy_draft_params)

    respond_to do |format|
      if @fantasy_draft.save

        Pusher['dashboard'].trigger('refresh_dashboard', {
          message: 'refreshing dashboard'
        })

        format.html { redirect_to fantasy_league_url(@fantasy_draft.fantasy_league_id), notice: 'Draft was successfully created.' }
        format.json { render :show, status: :created, location: @fantasy_draft }
      else
        format.html { render :new }
        format.json { render json: @fantasy_draft.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drafts/1
  # PATCH/PUT /drafts/1.json
  def update
    respond_to do |format|
      if @fantasy_draft.update(fantasy_draft_params)

        Pusher['dashboard'].trigger('refresh_dashboard', {
          message: 'refreshing dashboard'
        })

        if params[:fantasy_draft][:redirect_to].to_s == 'manager'
          format.html { redirect_to fantasy_league_fantasy_draft_manager_path(@fantasy_draft.fantasy_league_id, @fantasy_draft), notice: 'Draft was successfully updated.' }
        else
          format.html { redirect_to fantasy_league_url(@fantasy_draft.fantasy_league_id), notice: 'Draft was successfully updated.' }
        end

        format.json { render :show, status: :ok, location: @fantasy_draft }
      else
        format.html { render :edit }
        format.json { render json: @fantasy_draft.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drafts/1
  # DELETE /drafts/1.json
  def destroy
    @fantasy_draft.destroy
    respond_to do |format|
      format.html { redirect_to fantasy_league_url(@fantasy_draft.fantasy_league_id), notice: 'Draft was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fantasy_draft
      @fantasy_draft = FantasyDraft.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fantasy_draft_params
      params.require(:fantasy_draft).permit(:fantasy_league_id, :fantasy_draft_style_id, :player_id, :max_amount, :rounds)
    end
end

app/views/fantasy_drafts/_form.html.erb
<%= form_for([@fantasy_league, @fantasy_draft]) do |f| %>
  <%= f.hidden_field :fantasy_league_id %>

  <div class="field">
    <%= f.label :fantasy_draft_style_id %><br>
    <%= f.select :fantasy_draft_style_id, options_from_collection_for_select(FantasyDraftStyle.all, "id", "name", @fantasy_draft.fantasy_draft_style_id) %>

  </div>
  <div class="field">
    <%= f.label :max_amount %><br>
    <%= f.number_field :max_amount %>
  </div>
  <div class="field">
    <%= f.label :rounds %><br>
    <%= f.number_field :rounds %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fantasy_drafts/cheatsheet.erb
<div data-role="collapsible">
    <h4><center>Filter By Position</center></h4>
    <p>
      <a class="ui-btn" href="<%=fantasy_league_fantasy_draft_cheatsheet_path%>">All</a>
      <% Position.all.each do |position| %>
        <%= link_to position.name, fantasy_league_fantasy_draft_cheatsheet_path(:position_id => position.id), :class => 'ui-btn' %>
      <% end %>
    </p>
</div>

<form>
    <input id="filter-for-listview" data-type="search" placeholder="Type to search...">
</form>

<ul data-role="listview" data-inset="true" data-filter="true" data-input="#filter-for-listview">
  <% @player_ranks.each do |player_rank| %>
  <li>
    <% if params[:position_id] %>
        <%= player_rank.position_rank %>.
    <% else %>
        <%= player_rank.overall_rank %>.
    <% end %>
       <%= player_rank.player.name %> [<%= player_rank.player.position.name %>]  [<%= player_rank.player.team.key %>]

    <div style="float:right">
      <% if not player_rank.player.player_auction_value.nil?%>
        <% if player_rank.player.player_auction_value.avg_price != 0 %>
            $<%= player_rank.player.player_auction_value.avg_price %>
        <% else %>
            $1
        <% end %>
      <% else %>
          $1
      <% end %>
    </div>

  <% end %>
  </li>
</ul>

<script type="text/javascript">
  // Enable pusher logging - don't include this in production
  Pusher.log = function(message) {
    if (window.console && window.console.log) {
      window.console.log(message);
    }
  };

  var pusher = new Pusher('a85a38516f6db88b62ae');
  var channel = pusher.subscribe('dashboard');
  channel.bind('refresh_dashboard', function(data) {
    location.reload();
  });
</script>

app/views/fantasy_drafts/edit.html.erb
<h3><%= @fantasy_league.name %> | Draft Management</h3>
<%= link_to 'Set Draft Order', fantasy_league_fantasy_draft_fantasy_draft_orders_path(@fantasy_league, @fantasy_draft) %>

<%= render 'form' %>
<%= link_to 'Back', fantasy_league_path(@fantasy_league) %>

app/views/fantasy_drafts/index.html.erb
<h1>Listing drafts</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Fantasy league</th>
      <th>Fantasy draft style</th>
      <th>Player</th>
      <th>Max amount</th>
      <th>Rounds</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drafts.each do |draft| %>
      <tr>
        <td><%= draft.fantasy_league %></td>
        <td><%= draft.fantasy_draft_style %></td>
        <td><%= draft.player %></td>
        <td><%= draft.max_amount %></td>
        <td><%= draft.rounds %></td>
        <td><%= link_to 'Show', fantasy_draft %></td>
        <td><%= link_to 'Edit', edit_fantasy_draft_path(draft) %></td>
        <td><%= link_to 'Destroy', fantasy_draft, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Draft', new_fantasy_draft_path %>

app/views/fantasy_drafts/manager.html.erb
<h3><%= @fantasy_league.name %> | Manager Panel</h3>
<hr />


<div class="row-fluid">
  <div class="span6">
    <h4>Step 1: Set the "On the Block" Player</h4>
    <hr />

    <div class="well">

      <% if @fantasy_draft.player_id %>

        <center>
          <strong><%=@fantasy_draft.player.name%></strong> is currently "On the Block"
          <br />
          <br />
          <%= form_for([@fantasy_league, @fantasy_draft]) do |f| %>
            <%= f.hidden_field :redirect_to, :value => 'manager' %>
            <%= f.hidden_field :player_id, :value => nil %>
            <%= f.submit 'Unset this Player', :class => 'btn btn-small btn-danger' %>
          <% end %>
        </center>

      <% else %>

        <%= form_for([@fantasy_league, @fantasy_draft]) do |f| %>
          <%= f.hidden_field :redirect_to, :value => 'manager' %>
          <div class="field">
            <%= f.select :player_id, @players, {}, {:class => 'select2', :style => 'width:100%'} %>
          </div>
          <div class="actions">
            <%= f.submit 'Set the "On the Block" Player', :class => 'btn btn-primary' %>
          </div>
        <% end %>

        Can't find the player you are looking for? [<%= link_to 'Add New Player', new_player_path %>]



      <% end %>
    </div>

  </div>
  <div class="span6">
    <h4>Step 2: Add Draft Pick</h4>
    <hr />

    <div class="well" style="font-size:16px;">
      <% if @fantasy_draft.player_id %>

        <center>
          <strong><%=@fantasy_draft.player.name%></strong> has been drafted to:
          <br />
          <br />

          <%= form_for([@fantasy_league, @fantasy_draft, @fantasy_player]) do |f| %>
            <%= f.hidden_field :fantasy_league_id %>
            <%= f.hidden_field :fantasy_draft_id %>
            <%= f.hidden_field :player_id, :value => @fantasy_draft.player_id %>

            <%= f.select :fantasy_team_id, options_from_collection_for_select(@fantasy_league.fantasy_teams.order('owner'), "id", "owner_and_team"), {}, {:class => 'select2', :style => 'width:100%'}  %>
              <br />
              <br />
              for
              <br />
              <br />

              <div class="input-prepend">
                <span class="add-on">$</span>
                <%= f.number_field :price, :class => 'span5' %>
              </div>


              <br />
              <br />
              dollars
              <br />
              <br />
              <%= f.submit 'Finalize Draft Pick!', :class => 'btn btn-primary btn-small' %>
          <% end %>
          </center>
      <% else %>
        You must set a "On the Block" player to add a draft pick.
      <% end %>

    </div>

  </div>
</div>


<div class="row-fluid">
  <div class="span12">
    <h4>Previous Draft Picks</h4>
    <hr />
    <div class="well">

      <% if @fantasy_players.any? %>

        <table class="table">
          <thead>
            <tr>
              <th>Player</th>
              <th>Price Paid</th>
              <th>Team</th>
              <th>Owner</th>
              <th>Delete</th>
            </tr>
          </thead>

          <tbody>
            <% @fantasy_players.each do |fantasy_player| %>
              <tr>
                <td>
                   <%= fantasy_player.player.name %> (<%= fantasy_player.player.position.name %>) - <%= fantasy_player.player.team.key %>
                </td>
                <td>
                   $<%= fantasy_player.price %>
                </td>
                <td>
                   <%= fantasy_player.fantasy_team.name %>
                </td>
                <td>
                   <%= fantasy_player.fantasy_team.owner %>
                </td>
                <td>
                   <%= link_to 'Edit Pick', edit_fantasy_league_fantasy_draft_fantasy_player_path(@fantasy_league, @fantasy_draft, fantasy_player), :class => 'btn btn-small' %>

                   <%= link_to 'Delete Draft Pick', fantasy_league_fantasy_draft_fantasy_player_path(@fantasy_league, @fantasy_draft, fantasy_player), :class => 'btn btn-small btn-danger', method: :delete, data: { confirm: 'Are you sure you want to delete this pick?' } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        There has been no draft picks yet.
      <% end %>

    </div>
  </div>
</div>

app/views/fantasy_drafts/new.html.erb
<h3><%= @fantasy_league.name %> | Draft Management</h3>

<%= render 'form' %>

<%= link_to 'Back', fantasy_league_path(@fantasy_league) %>

app/views/fantasy_drafts/players.erb
<div data-role="collapsible">
    <h4><center>Filter By Position</center></h4>
    <p>
      <a class="ui-btn" href="<%=fantasy_league_fantasy_draft_players_path%>">All</a>
      <% Position.all.each do |position| %>
        <%= link_to position.name, fantasy_league_fantasy_draft_players_path(:position_id => position.id), :class => 'ui-btn' %>
      <% end %>
    </p>
</div>

<form>
    <input id="filter-for-listview" data-type="search" placeholder="Type to search...">
</form>

<ul data-role="listview" data-inset="true" data-filter="true" data-input="#filter-for-listview">
  <% @player_ranks.each do |player_rank| %>
  <li>
    <% if params[:position_id] %>
        <%= player_rank.position_rank %>.
    <% else %>
        <%= player_rank.overall_rank %>.
    <% end %>
       <%= player_rank.player.name %> [<%= player_rank.player.position.name %>]  [<%= player_rank.player.team.key %>]

    <div style="float:right">
      <% if not player_rank.player.player_auction_value.nil?%>
        <% if player_rank.player.player_auction_value.avg_price != 0 %>
            $<%= player_rank.player.player_auction_value.avg_price %>
        <% else %>
            $1
        <% end %>
      <% else %>
          $1
      <% end %>
    </div>

  <% end %>
  </li>
</ul>

<script type="text/javascript">
  // Enable pusher logging - don't include this in production
  Pusher.log = function(message) {
    if (window.console && window.console.log) {
      window.console.log(message);
    }
  };

  var pusher = new Pusher('a85a38516f6db88b62ae');
  var channel = pusher.subscribe('dashboard');
  channel.bind('refresh_dashboard', function(data) {
    location.reload();
  });
</script>

app/views/fantasy_drafts/report.erb
<div class="row-fluid">
    <div class="span12">

        <h4>Fantasy Draft Report Card</h4>
        <hr />
        <br />

        <%
            @fantasy_league.fantasy_teams.each do |fantasy_team|

                @fantasy_players = FantasyPlayer.where(
                                                    fantasy_team_id: fantasy_team.id,
                                                    fantasy_draft_id: params[:fantasy_draft_id],
                                                    fantasy_league_id: params[:fantasy_league_id]
                                                ).order('id DESC')

        %>

            <h3><%= fantasy_team.name %> <small>[<%= fantasy_team.owner %>]</small></h3>
            <table class="table table-bordered">
              <thead>
                <tr>
                  <th width="90%">Player</th>
                  <th width="10%">Price Paid</th>
                </tr>
              </thead>

              <tbody>
                <% @fantasy_players.each do |fantasy_player| %>
                  <tr>
                    <td>
                       <%= fantasy_player.player.last_name %>, <%= fantasy_player.player.first_name %>
                    </td>
                    <td>$<%= fantasy_player.price %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <hr />
            <br />


        <% end %>

    </div>
</div>

app/views/fantasy_drafts/show.html.erb
<div class="container-fluid" style="height:100%;">

    <div class="row-fluid">
        <div class="span12 draft_board_league_row">
            <div class="draft_board_league_name">
                <%=@fantasy_league.name%>
            </div>
        </div>
    </div>


    <div class="row-fluid">
        <div class="span12">
            <ul class="draft_order">
                <% @fantasy_order.each do |fantasy_team| %>
                    <li class="draft_order__slot">
                        <%= fantasy_team.name %>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span10">

            <div id="draft_board">
                <ul class="draft_board__round_column">
                    <li style="border-bottom:none">
                        &nbsp;
                    </li>
                    <li style="height:20px;">
                        &nbsp;
                    </li>
                    <% @fantasy_draft.rounds.times do |round| round = round + 1 %>
                        <li>
                            <%=round%>
                        </li>
                    <% end %>
                </ul>

                <%
                    @fantasy_draft_orders.each do |fantasy_draft_order|
                        fantasy_players = FantasyPlayer
                                                .where(
                                                    fantasy_draft_id: params[:id],
                                                    fantasy_league_id: params[:fantasy_league_id],
                                                    fantasy_team_id: fantasy_draft_order.fantasy_team.id
                                                ).order('id ASC')

                        team_rounds = @fantasy_draft.rounds.to_i - fantasy_players.size.to_i

                        total_spent = 0;

                        if fantasy_players.any?
                            fantasy_players.each do |fantasy_player|
                                total_spent += fantasy_player.price
                            end
                        end

                        max_bid = (@fantasy_draft.max_amount - total_spent - (@fantasy_draft.rounds - fantasy_players.size.to_i)) + 1


                %>
                    <ul class="draft_board__column">
                        <li style="border-bottom:none">
                            <%=fantasy_draft_order.fantasy_team.name%>
                        </li>
                        <li style="text-align:center; line-height: 15px; font-size:12px; height:20px; ">
                            Max: $<%=max_bid%>
                        </li>
                        <%
                            if fantasy_players.any?
                                fantasy_players.each do |fantasy_player|
                        %>
                                    <li class="<%=fantasy_player.player.position.name%>">
                                        <div class="draft_pick_card">
                                            <span class="label label-info pull-left">
                                                <%=fantasy_player.player.position.name%>
                                            </span>
                                            <span class="label label-info pull-right">
                                                $<%=fantasy_player.price%>
                                            </span>
                                            <div class="first_name">
                                                <%=truncate(fantasy_player.player.first_name, :length => 10, :separator => '')%>
                                            </div>
                                            <div class="last_name">
                                                <%=truncate(fantasy_player.player.last_name, :length => 10, :separator => '')%>
                                            </div>

                                        </div>
                                    </li>
                        <%
                                end
                            end
                        %>

                        <% team_rounds.times do |round| round = round + 1  %>
                            <li>

                            </li>
                        <% end %>
                    </ul>
                <% end %>

            </div>
        </div>
        <div class="span2" style="margin-left:10px">

            <% if @fantasy_draft.player_id %>
                <div class="otb_container">
                    <div class="otb_info">

                        <div class="team_logo pull-left">
                            <%= image_tag("team_logos/#{@fantasy_draft.player.team.key}.png", width: "50", alt: @fantasy_draft.player.team.name)%>
                        </div>

                        <div class="first_name">
                            <%= @fantasy_draft.player.first_name %>
                        </div>

                        <div class="last_name">
                            <%= @fantasy_draft.player.last_name %>
                        </div>

                        <div class="clearfix"></div>


                        <table class="otb_table">
                            <tbody>
                                <% if not @fantasy_draft.player.position.nil? %>
                                    <tr>
                                        <td class="title">
                                            Position:
                                        </td>
                                        <td class="stat">
                                            <%= @fantasy_draft.player.position.name %>
                                        </td>
                                    </tr>
                                <% end %>

                                <% if @fantasy_draft.player.uniform_number && @fantasy_draft.player.uniform_number.to_s != '0'%>
                                    <tr>
                                        <td class="title">
                                            Number:
                                        </td>
                                        <td class="stat">
                                            #<%= @fantasy_draft.player.uniform_number %>
                                        </td>
                                    </tr>
                                <% end %>
                                <% if not @fantasy_draft.player.height.empty? %>
                                    <tr>
                                        <td class="title">
                                            Height:
                                        </td>
                                        <td class="stat">
                                            <%= @fantasy_draft.player.height %>
                                        </td>
                                    </tr>
                                <% end %>
                                <% if not @fantasy_draft.player.weight.empty? %>
                                    <tr>
                                        <td class="title">
                                            Weight:
                                        </td>
                                        <td class="stat">
                                            <%= @fantasy_draft.player.weight %> lbs
                                        </td>
                                    </tr>
                                <% end %>
                                <% if @fantasy_draft.player.date_of_birth.to_s != '0000-00-00' %>
                                    <tr>
                                        <td class="title">
                                            Age:
                                        </td>
                                        <td class="stat">
                                            <%= @fantasy_draft.player.age %>
                                        </td>
                                    </tr>
                                <% end %>
                                <% if not @fantasy_draft.player.college.empty? %>
                                    <tr>
                                        <td class="title">
                                            College:
                                        </td>
                                        <td class="stat">
                                            <%= @fantasy_draft.player.college %>
                                        </td>
                                    </tr>
                                <% end %>
                                <% if @fantasy_draft.player.team.bye.week %>
                                    <tr>
                                        <td class="title">
                                            Bye Week:
                                        </td>
                                        <td class="stat">
                                            Week <%= @fantasy_draft.player.team.bye.week %>
                                        </td>
                                    </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>

            <% else %>
                <div class="next_pick_container">
                    <div class="next_pick">
                        Next Draft Pick
                    </div>
                    <div class="name">
                        <%= @fantasy_order.first.name %>
                    </div>
                    <div class="owner">
                        <%= @fantasy_order.first.owner %>
                    </div>
                </div>

            <% end %>


            <div class="previous_draft_picks">

                <table class="table">
                    <thead>
                        <tr>
                            <th>Previous Picks</th>
                            <th>Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        <%@fantasy_players.each do |fantasy_player| %>
                            <tr>
                                <td>
                                    <%= fantasy_player.player.name %>
                                    <br />
                                    <small>
                                        <%= fantasy_player.fantasy_team.name %>
                                    </small>
                                </td>
                                <td>$<%= fantasy_player.price %></td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>

            </div>
        </div>
    </div>


</div>


<script type="text/javascript">
    // Enable pusher logging - don't include this in production
    Pusher.log = function(message) {
      if (window.console && window.console.log) {
        window.console.log(message);
      }
    };

    var pusher = new Pusher('a85a38516f6db88b62ae');
    var channel = pusher.subscribe('dashboard');
    channel.bind('refresh_dashboard', function(data) {
      location.reload();
    });
  </script>