config/routes.rb
Rails.application.routes.draw do
  resources :fantasy_drafts
  resources :fantasy_draft_orders
  resources :fantasy_draft_styles
  resources :fantasy_players
  resources :fantasy_teams
  resources :fantasy_leagues
  resources :player_auction_values
  resources :player_projections
  resources :player_ranks
  resources :players
  resources :positions
  resources :byes
  resources :schedules
  resources :teams
  resources :leagues

  resources :fantasy_leagues do
    resources :fantasy_drafts
    resources :fantasy_teams do
      resources :fantasy_players
    end
    resources :fantasy_drafts do
      get '/manager', to: 'fantasy_drafts#manager'
      get '/cheatsheet', to: 'fantasy_drafts#cheatsheet'
      get '/report', to: 'fantasy_drafts#report'
      resources :fantasy_players
      resources :fantasy_draft_orders
    end
  end

  root 'fantasy_leagues#index'
end

app/models/bye.rb
class Bye < ActiveRecord::Base
  belongs_to :team
end

app/models/fantasy_draft.rb
class FantasyDraft < ActiveRecord::Base
  belongs_to :fantasy_league
  belongs_to :fantasy_draft_style
  belongs_to :player

end

app/models/fantasy_draft_order.rb
class FantasyDraftOrder < ActiveRecord::Base
  belongs_to :fantasy_league
  belongs_to :fantasy_team
  belongs_to :fantasy_draft
end

app/models/fantasy_draft_style.rb
class FantasyDraftStyle < ActiveRecord::Base
end

app/models/fantasy_league.rb
class FantasyLeague < ActiveRecord::Base
    has_many :fantasy_teams
    has_many :fantasy_drafts
end

app/models/fantasy_player.rb
class FantasyPlayer < ActiveRecord::Base
  belongs_to :fantasy_league
  belongs_to :fantasy_team
  belongs_to :fantasy_draft
  belongs_to :player
end

app/models/fantasy_team.rb
class FantasyTeam < ActiveRecord::Base
    belongs_to :fantasy_league


    def name_and_owner
        "#{name} - #{owner}"
    end

    def owner_and_team
        "#{owner} - #{name}"
    end

end

app/models/league.rb
class League < ActiveRecord::Base
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :league
  belongs_to :team
  belongs_to :position
  has_one :player_auction_value
  has_one :player_projection
  has_one :player_rank

    def age
      (Time.now.to_s(:number).to_i - date_of_birth.to_time.to_s(:number).to_i)/10e9.to_i
    end

end

app/models/player_projection.rb
class PlayerProjection < ActiveRecord::Base
  belongs_to :player
  has_one :team, through: :player
  has_one :position, through: :player
end

app/models/player_rank.rb
class PlayerRank < ActiveRecord::Base
  belongs_to :player
  has_one :team, through: :player
  has_one :position, through: :player
end

app/models/position.rb
class Position < ActiveRecord::Base
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :away_team, class_name: "Team", foreign_key: "away_team_id"
  belongs_to :home_team, class_name: "Team", foreign_key: "home_team_id"
end

app/models/team.rb
class Team < ActiveRecord::Base
    belongs_to :league
    has_many :players
    has_many :schedules
    has_one :bye

    def full_name
        "#{city} #{name}"
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.includes(:team, :position).order(:last_name)
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:league_id, :team_id, :position_id, :ffn_player_id, :college, :first_name, :last_name, :name, :height, :weight, :uniform_number, :date_of_birth, :active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/byes_helper.rb
module ByesHelper
end

app/helpers/drafts_helper.rb
module DraftsHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :league_id %><br>
    <%= f.select :league_id, options_from_collection_for_select(League.all.order('name'), "id", "name", @player.league_id) %>
  </div>
  <div class="field">
    <%= f.label :team_id %><br>
    <%= f.select :team_id, options_from_collection_for_select(Team.all, "id", "full_name", @player.team_id) %>
  </div>
  <div class="field">
    <%= f.label :position_id %><br>
    <%= f.select :position_id, options_from_collection_for_select(Position.all, "id", "name", @player.position_id) %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :uniform_number %><br>
    <%= f.text_field :uniform_number %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br>
    <%= f.text_field :date_of_birth %>
  </div>
  <div class="field">
    <%= f.label :college %><br>
    <%= f.text_field :college %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h4>Players</h4>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td>
        <%= image_tag("team_logos/#{player.team.key}.png", width: "25", alt: player.team.name)%>
           <%= player.last_name %>, <%= player.first_name %> (<%= player.position.name %>)
        </td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>League:</strong>
  <%= @player.league.name %>
</p>

<p>
  <strong>Team:</strong>
  <%= @player.team.full_name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @player.position.name %>
</p>


<p>
  <strong>First name:</strong>
  <%= @player.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @player.last_name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Height:</strong>
  <%= @player.height %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @player.weight %>
</p>

<p>
  <strong>Uniform number:</strong>
  <%= @player.uniform_number %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @player.date_of_birth %>
</p>

<p>
  <strong>Active:</strong>
  <%= @player.active %>
</p>

<p>
  <strong>College:</strong>
  <%= @player.college %>
</p>


<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>